export const COMPLETE_DEMO_DATA: Record<string, any[]> = {
  "clients": [
    {
      "id": "demo-cli_1",
      "name": "Poulina Group Holding",
      "email": "contact@poulina.com.tn",
      "phone": "+216 71 130 000",
      "address": "GP1 Km 12, Ezzahra, Ben Arous, Tunisie",
      "category": "Local",
      "sector": "Agro-alimentaire & Distribution",
      "revenuePotential": 250000,
      "status": "Active",
      "createdDate": "2026-01-10",
      "notes": "Partenaire commercial historique majeur. Très exigeant sur les délais de livraison logistique.",
      "engagements": [
        {
          "id": "demo-eng_1_1",
          "title": "Garantie de livraison sous 48h",
          "description": "Assurer la réception des commandes de volaille brute en moins de 48h sur le site de Sfax.",
          "dueDate": "2026-07-15",
          "status": "Met",
          "is_demo": true
        },
        {
          "id": "demo-eng_1_2",
          "title": "Mise à disposition de conteneurs isothermes",
          "description": "Fournir 25 conteneurs réfrigérés de dernière génération en crédit-bail.",
          "dueDate": "2026-10-30",
          "status": "Pending",
          "is_demo": true
        }
      ],
      "is_demo": true
    },
    {
      "id": "demo-cli_2",
      "name": "Sousse Textiles Export S.A.",
      "email": "export@soussetextiles.tn",
      "phone": "+216 73 224 500",
      "address": "Zone Industrielle Sidi Abdelhamid, Sousse, Tunisie",
      "category": "Export",
      "sector": "Textile & Habillement",
      "revenuePotential": 480000,
      "status": "Active",
      "createdDate": "2026-02-15",
      "notes": "Client exportant vers la France et l'Allemagne. Exige des certificats de conformité de qualité stricts.",
      "engagements": [
        {
          "id": "demo-eng_2_1",
          "title": "Attestation OEKO-TEX Standard 100",
          "description": "Fournir les certificats de traçabilité matière avant chaque expédition.",
          "dueDate": "2026-06-30",
          "status": "Met",
          "is_demo": true
        },
        {
          "id": "demo-eng_2_2",
          "title": "Paiement en Euros à 60 jours",
          "description": "Respecter l'échéance de paiement par virement Swift direct.",
          "dueDate": "2026-08-20",
          "status": "Pending",
          "is_demo": true
        }
      ],
      "is_demo": true
    },
    {
      "id": "demo-cli_3",
      "name": "Société Carthage Cement",
      "email": "approvisionnement@carthagecement.tn",
      "phone": "+216 71 987 654",
      "address": "Rue du Lac de Côme, Les Berges du Lac, Tunis",
      "category": "Local",
      "sector": "Construction & Cimenterie",
      "revenuePotential": 180000,
      "status": "Active",
      "createdDate": "2025-11-05",
      "notes": "Compte clé étatique tunisien. Les processus de recouvrement sont lents et assujettis à une retenue à la source systématique.",
      "engagements": [
        {
          "id": "demo-eng_3_1",
          "title": "Approvisionnement en gypse brut",
          "description": "Livrer 500 tonnes de gypse raffiné par mois sur le site de Djebel Ressas.",
          "dueDate": "2026-07-01",
          "status": "Delayed",
          "is_demo": true
        }
      ],
      "is_demo": true
    },
    {
      "id": "demo-cli_4",
      "name": "Magasin Général (MG) Tunisie",
      "email": "finances@mg.com.tn",
      "phone": "+216 71 840 111",
      "address": "Avenue de France, Tunis, Tunisie",
      "category": "Local",
      "sector": "Grande Distribution",
      "revenuePotential": 320000,
      "status": "Active",
      "createdDate": "2026-03-01",
      "notes": "Réseau de supermarchés national. Très sensible aux opérations promotionnelles de fin d'année.",
      "engagements": [
        {
          "id": "demo-eng_4_1",
          "title": "Taux de service linéaire à 98%",
          "description": "Assurer aucun rupture de stock sur les produits de notre marque.",
          "dueDate": "2026-09-01",
          "status": "Pending",
          "is_demo": true
        }
      ],
      "is_demo": true
    }
  ],
  "complaints": [
    {
      "id": "demo-rec_1",
      "clientId": "cli_1",
      "clientName": "Poulina Group Holding",
      "subject": "Retard de livraison sur la commande de Sfax #8940",
      "description": "Le camion frigorifique est arrivé avec 6 heures de retard sur le planning convenu. Les équipes de déchargement n'étaient plus disponibles, générant un surcoût logistique et un risque pour la chaîne du froid.",
      "status": "In_Investigation",
      "priority": "High",
      "assignedDepartment": "Logistics",
      "investigationDetails": "Le transporteur externe a subi une panne moteur à hauteur de Sousse (autoroute A1). Des mesures de backup n'ont pas été activées à temps.",
      "createdDate": "2026-06-10",
      "is_demo": true
    },
    {
      "id": "demo-rec_2",
      "clientId": "cli_2",
      "clientName": "Sousse Textiles Export S.A.",
      "subject": "Anomalie d'épaisseur de fil sur le lot TX-09",
      "description": "Une déviation d'élasticité de 15% supérieure aux tolérances de la fiche de spécifications a été identifiée sur les bobines de fil de coton écru.",
      "status": "Resolved",
      "priority": "High",
      "assignedDepartment": "Quality",
      "investigationDetails": "Après analyse du laboratoire, le degré d'humidité stocké au dépôt logistique était sursaturé. Un re-conditionnement thermique a été réalisé.",
      "resolutionNotes": "Le lot non conforme a été récupéré et remplacé sous 5 jours. Un avoir de 10% de dédommagement commercial a été validé.",
      "createdDate": "2026-06-12",
      "resolvedDate": "2026-06-16",
      "is_demo": true
    },
    {
      "id": "demo-rec_3",
      "clientId": "cli_3",
      "clientName": "Société Carthage Cement",
      "subject": "Erreur de calibrage sur la livraison de gypse",
      "description": "La granulométrie livrée dépasse 40mm alors que l'engagement technique exige un d90 inférieur à 20mm.",
      "status": "Received",
      "priority": "Medium",
      "assignedDepartment": "Production",
      "createdDate": "2026-06-17",
      "is_demo": true
    }
  ],
  "invoices": [
    {
      "id": "FAC-2026-0881",
      "clientId": "CLI-WEB-881",
      "clientName": "Société du Sahel Distribution",
      "invoiceNumber": "FAC-2026-0881",
      "sales_channel": "web",
      "warehouse_location": "Entrepôt Principal - Z.I. Charguia II + Magasin Tunis Principal - Av. Bourguiba",
      "warehouses_involved": [
        "Entrepôt Principal - Z.I. Charguia II",
        "Magasin Tunis Principal - Av. Bourguiba"
      ],
      "multi_depot_tag": "📍 2 Dépôts impliqués (Charguia II + Tunis)",
      "delivery_address": "Zone Industrielle Akouda, Lot 14, Sousse",
      "amountHT": 9800,
      "vatRate": 19,
      "vatAmount": 1862,
      "withholdingTaxRate": 1.5,
      "withholdingAmount": 147,
      "amountTTC": 11662,
      "amountNetToPay": 11515,
      "status": "Unpaid",
      "delivery_status": "en_attente",
      "issuedDate": "2026-08-10T08:00:00.000Z",
      "dueDate": "2026-09-10T08:00:00.000Z",
      "items": [
        {
          "code": "PROD-BTP-001",
          "description": "40 Sacs Ciment Portland CEM I + 15 Palettes Briques (Ramassage Charguia II)",
          "quantity": 55,
          "unitPrice": 100,
          "totalTTC": 5500
        },
        {
          "code": "PROD-PNT-006",
          "description": "6 Pots Peinture Industrielle + 18 Rouleaux Câbles Armés (Ramassage Tunis Bourguiba)",
          "quantity": 24,
          "unitPrice": 256.75,
          "totalTTC": 6162
        }
      ],
      "recouvrementSteps": [],
      "is_demo": true
    },
    {
      "id": "FAC-2026-0900",
      "clientId": "CLI-GTS-900",
      "clientName": "Grands Travaux du Sud - GTS",
      "invoiceNumber": "FAC-2026-0900",
      "sales_channel": "field_sales",
      "commercial_id": "EMP-COM-01",
      "commercial_name": "Sami Cherif (Commercial Terrain)",
      "warehouse_location": "Entrepôt Principal - Z.I. Charguia II + Magasin Tunis Principal + Stock Logistique Sousse",
      "warehouses_involved": [
        "Entrepôt Principal - Z.I. Charguia II",
        "Magasin Tunis Principal",
        "Stock Logistique Sousse"
      ],
      "multi_depot_tag": "📍 3 Dépôts impliqués (Charguia II + Tunis + Sousse)",
      "delivery_address": "Chantier Autoroute A1, Km 140, Sfax",
      "amountHT": 20882.35,
      "vatRate": 19,
      "vatAmount": 3967.65,
      "withholdingTaxRate": 1.5,
      "withholdingAmount": 313.24,
      "amountTTC": 24850,
      "amountNetToPay": 24536.76,
      "status": "Unpaid",
      "delivery_status": "en_attente",
      "issuedDate": "2026-08-10T08:00:00.000Z",
      "dueDate": "2026-09-25T08:00:00.000Z",
      "items": [
        {
          "code": "PROD-STC-100",
          "description": "Armatures Acier BTP 12mm (Ramassage Charguia II)",
          "quantity": 100,
          "unitPrice": 120,
          "totalTTC": 12000
        },
        {
          "code": "PROD-OUT-020",
          "description": "Outillage Coffrage Lourd (Ramassage Magasin Tunis Principal)",
          "quantity": 20,
          "unitPrice": 282.5,
          "totalTTC": 5650
        },
        {
          "code": "PROD-AGG-050",
          "description": "Grave Bitume Routier (Ramassage Stock Logistique Sousse)",
          "quantity": 50,
          "unitPrice": 144,
          "totalTTC": 7200
        }
      ],
      "recouvrementSteps": [],
      "is_demo": true
    },
    {
      "id": "POS-2026-0104",
      "clientId": "CLI-POS-104",
      "clientName": "Comptoir BTP Ariana",
      "invoiceNumber": "POS-2026-0104",
      "sales_channel": "pos",
      "seller_id": "EMP-POS-01",
      "seller_name": "Mounir Karray (Chef de Caisse)",
      "warehouse_location": "Magasin Principal Tunis",
      "delivery_address": "Chantier Résidence Les Jasmins, Ariana",
      "amountHT": 8500,
      "vatRate": 19,
      "vatAmount": 1615,
      "withholdingTaxRate": 1.5,
      "withholdingAmount": 127.5,
      "amountTTC": 10115,
      "amountNetToPay": 9987.5,
      "status": "Paid",
      "delivery_status": "en_attente",
      "issuedDate": "2026-08-10T08:00:00.000Z",
      "dueDate": "2026-08-10T08:00:00.000Z",
      "items": [
        {
          "code": "PROD-ALU-002",
          "description": "Profilés Aluminium Anodisé 6m",
          "quantity": 70,
          "unitPrice": 145,
          "totalTTC": 10115
        }
      ],
      "recouvrementSteps": [],
      "is_demo": true
    },
    {
      "id": "COM-2026-0052",
      "clientId": "CLI-FIELD-052",
      "clientName": "Établissements Trabelsi Sousse",
      "invoiceNumber": "COM-2026-0052",
      "sales_channel": "field_sales",
      "commercial_id": "EMP-COM-01",
      "commercial_name": "Sami Cherif (Commercial Terrain)",
      "warehouse_location": "Dépôt Central Charguia",
      "delivery_address": "Avenue Habib Bourguiba, Nabeul",
      "amountHT": 3100,
      "vatRate": 19,
      "vatAmount": 589,
      "withholdingTaxRate": 1.5,
      "withholdingAmount": 46.5,
      "amountTTC": 3689,
      "amountNetToPay": 3642.5,
      "status": "Unpaid",
      "delivery_status": "en_attente",
      "issuedDate": "2026-08-10T08:00:00.000Z",
      "dueDate": "2026-09-10T08:00:00.000Z",
      "items": [
        {
          "code": "PROD-BTP-001",
          "description": "Ciment Portland CEM I 42.5",
          "quantity": 200,
          "unitPrice": 18.445,
          "totalTTC": 3689
        }
      ],
      "recouvrementSteps": [],
      "is_demo": true
    },
    {
      "id": "demo-inv_1",
      "clientId": "cli_1",
      "clientName": "Poulina Group Holding",
      "invoiceNumber": "FA-2026-0012",
      "amountHT": 25000,
      "vatRate": 19,
      "vatAmount": 4750,
      "withholdingTaxRate": 1.5,
      "withholdingAmount": 446.25,
      "amountTTC": 29750,
      "amountNetToPay": 29303.75,
      "status": "Paid",
      "issuedDate": "2026-05-02",
      "dueDate": "2026-06-15",
      "collectedAmount": 29303.75,
      "withholdingCertificateReceived": true,
      "recouvrementSteps": [
        {
          "id": "demo-step_1",
          "date": "2026-06-01",
          "type": "Email",
          "note": "Relance hebdomadaire automatique - envoi de la facture numérique.",
          "performedBy": "Système Facturation",
          "is_demo": true
        },
        {
          "id": "demo-step_2",
          "date": "2026-06-10",
          "type": "Call",
          "note": "Appel service comptable Poulina. Virement programmé pour le 14/06. Certificat de retenue transmis par mail.",
          "performedBy": "Zied Ben Miled",
          "is_demo": true
        }
      ],
      "is_demo": true
    },
    {
      "id": "demo-inv_2",
      "clientId": "cli_3",
      "clientName": "Société Carthage Cement",
      "invoiceNumber": "FA-2026-0018",
      "amountHT": 45000,
      "vatRate": 19,
      "vatAmount": 8550,
      "withholdingTaxRate": 1.5,
      "withholdingAmount": 803.25,
      "amountTTC": 53550,
      "amountNetToPay": 52746.75,
      "status": "Debt_Collection",
      "issuedDate": "2026-04-10",
      "dueDate": "2026-05-25",
      "collectedAmount": 0,
      "withholdingCertificateReceived": false,
      "recouvrementSteps": [
        {
          "id": "demo-step_3",
          "date": "2026-05-28",
          "type": "Email",
          "note": "Facture en souffrance. Demande d'état de validation de paiement émise à la direction administrative.",
          "performedBy": "Service Recouvrement",
          "is_demo": true
        },
        {
          "id": "demo-step_4",
          "date": "2026-06-05",
          "type": "Call",
          "note": "Contact téléphonique auprès du responsable trésorerie. Dossier en attente de visa du contrôleur d'État.",
          "performedBy": "Responsable Financier",
          "is_demo": true
        },
        {
          "id": "demo-step_5",
          "date": "2026-06-15",
          "type": "Letter",
          "note": "Envoi d'un courrier de mise en demeure amiable recommandé avec accusé de réception.",
          "performedBy": "Service Audit Interne",
          "is_demo": true
        }
      ],
      "is_demo": true
    },
    {
      "id": "demo-inv_3",
      "clientId": "cli_2",
      "clientName": "Sousse Textiles Export S.A.",
      "invoiceNumber": "FA-2026-0021",
      "amountHT": 12000,
      "vatRate": 0,
      "vatAmount": 0,
      "withholdingTaxRate": 0,
      "withholdingAmount": 0,
      "amountTTC": 12000,
      "amountNetToPay": 12000,
      "status": "Unpaid",
      "issuedDate": "2026-05-20",
      "dueDate": "2026-07-05",
      "collectedAmount": 0,
      "withholdingCertificateReceived": false,
      "recouvrementSteps": [],
      "is_demo": true
    },
    {
      "id": "demo-inv_4",
      "clientId": "cli_4",
      "clientName": "Magasin Général (MG) Tunisie",
      "invoiceNumber": "FA-2026-0025",
      "amountHT": 850,
      "vatRate": 19,
      "vatAmount": 161.5,
      "withholdingTaxRate": 1.5,
      "withholdingAmount": 0,
      "amountTTC": 1011.5,
      "amountNetToPay": 996.327,
      "status": "Unpaid",
      "issuedDate": "2026-06-15",
      "dueDate": "2026-07-30",
      "collectedAmount": 0,
      "withholdingCertificateReceived": false,
      "recouvrementSteps": [],
      "is_demo": true
    },
    {
      "id": "demo-inv_5",
      "clientId": "cli_4",
      "clientName": "Magasin Général (MG) Tunisie",
      "invoiceNumber": "FA-2026-0026",
      "amountHT": 500,
      "vatRate": 19,
      "vatAmount": 95,
      "withholdingTaxRate": 1.5,
      "withholdingAmount": 0,
      "amountTTC": 595,
      "amountNetToPay": 595,
      "status": "Draft",
      "issuedDate": "2026-06-17",
      "dueDate": "2026-08-01",
      "collectedAmount": 0,
      "withholdingCertificateReceived": false,
      "recouvrementSteps": [],
      "is_demo": true
    }
  ],
  "visitReports": [
    {
      "id": "demo-vis_1",
      "clientId": "cli_1",
      "clientName": "Poulina Group Holding",
      "date": "2026-06-08",
      "purpose": "Négociation annuelle & Revue Logistique",
      "summary": "Rencontre avec Mme Sonia Ben Slimane, Directrice des Achats. Poulina exprime une satisfaction globale sur la qualité de nos produits, mais formule un mécontentement critique concernant les retards de transport de la semaine dernière. Elle menace d'ouvrir un appel d'offres à des concurrents turcs ou espagnols si un taux de livraison sous 48h n'est pas garanti par contrat.",
      "actionPoints": [
        "Soumettre un plan de continuité d'activité (PCA) logistique au secrétariat des achats de Poulina avant le 25 juin.",
        "Vérifier auprès de l'équipe logistique s'il est possible de mobiliser des chauffeurs de réserve à Sfax.",
        "Renouveler l'offre tarifaire annuelle avec une remise préférentielle de 1.5% sur les volumes excédant 100 tonnes."
      ],
      "aiAnalyzed": true,
      "aiInsights": "ANALYSE STRATÉGIQUE (IA):\n- Risque de désabonnement client : ÉLEVÉ. Poulina est approchée activement par la concurrence étrangère.\n- Point de vigilance : Les retards logistiques sont les principaux déclencheurs de volatilité.\n- Recommandation IA : Intégrer une clause contractuelle de pénalité de retard légère en échange d'une exclusivité d'approvisionnement.",
      "author": "Zied Ben Miled",
      "is_demo": true
    },
    {
      "id": "demo-vis_2",
      "clientId": "cli_2",
      "clientName": "Sousse Textiles Export S.A.",
      "date": "2026-06-14",
      "purpose": "Vérification des normes d'intégration et nouveaux besoins filature",
      "summary": "Visite technique des usines à Sidi Abdelhamid. Validation du bon stockage thermique pour corriger l'humidité. Discussion sur un nouveau besoin pour l'année prochaine : fourniture de fil recyclé certifié GRS (Global Recycled Standard) pour répondre aux exigences d'un marché d'exportation de vêtements éco-conçus en Europe.",
      "actionPoints": [
        "Rechercher des fournisseurs certifiés de gousses de coton biologique recyclé sur le marché local.",
        "Établir une étude de rentabilité de la production de fils GRS.",
        "Lancer une offre technique chiffrée pour 10 tonnes de fils haut de gamme en juillet."
      ],
      "aiAnalyzed": false,
      "author": "Karim Chahed (Ingénieur Commercial)",
      "is_demo": true
    }
  ],
  "competitors": [
    {
      "id": "demo-comp_1",
      "competitorName": "Eurasia Import-Export (Turquie)",
      "sectorName": "Agro-alimentaire & Importations Générales",
      "strengths": [
        "Prix agressifs en raison de la dépréciation de la Livre Turque",
        "Fret maritime subventionné",
        "Gamme produit très automatisée"
      ],
      "weaknesses": [
        "Délais d'acheminement de 5 à 7 jours vers le port de Radès",
        "Frais de douane élevés hors accords préférentiels",
        "Absence de support client réactif en Tunisie"
      ],
      "pricingIndex": "Cheap",
      "marketShare": 15,
      "strategicWatchNote": "Propose régulièrement des prix inférieurs de 15% à nos tarifs aux clients tunisiens de grande distribution. Toutefois, leur manque de flexibilité logistique est notre principal atout de défense.",
      "recordedDate": "2026-05-12",
      "is_demo": true
    },
    {
      "id": "demo-comp_2",
      "competitorName": "SOTUMAR (Société Tunisienne des Matériaux)",
      "sectorName": "Construction & Cimenterie",
      "strengths": [
        "Forte implantation locale dans le sud tunisien (Gabès)",
        "Réseau d'approvisionnement ferroviaire dédié",
        "Appuis étatiques"
      ],
      "weaknesses": [
        "Outil industriel vieillissant sujet à des arrêts intempestifs",
        "Absence de filière export haut de gamme",
        "Rapports clients de type bureaucratique"
      ],
      "pricingIndex": "Competitive",
      "marketShare": 35,
      "strategicWatchNote": "Leader historique local, mais commence à perdre des parts de marché face à Carthage Cement sur les produits fins en raison d'un manque d'investissement dans l'assurance qualité.",
      "recordedDate": "2026-06-01",
      "is_demo": true
    }
  ],
  "suppliers": [
    {
      "id": "demo-sup_1",
      "name": "Tunisie Chimie Industrielle (TCI)",
      "contactName": "M. Hédi Boussaid",
      "email": "hboussaid@tci.com.tn",
      "phone": "+216 71 888 222",
      "address": "Zone Industrielle de Charguia II, Tunis",
      "category": "Chimie",
      "status": "Active",
      "createdDate": "2026-01-15",
      "is_demo": true
    },
    {
      "id": "demo-sup_2",
      "name": "Med Pack Sousse",
      "contactName": "Mme Amel Belcadhi",
      "email": "abelcadhi@medpack.com.tn",
      "phone": "+216 73 345 120",
      "address": "Zone Industrielle de Kalaa Kebira, Sousse",
      "category": "Emballage",
      "status": "Active",
      "createdDate": "2026-02-10",
      "is_demo": true
    },
    {
      "id": "demo-sup_3",
      "name": "Cotonière du Nord",
      "contactName": "M. Moncef Gharbi",
      "email": "m.gharbi@cotonniere.tn",
      "phone": "+216 72 456 789",
      "address": "Route de Béja, Mateur, Tunisie",
      "category": "Textile",
      "status": "Active",
      "createdDate": "2026-03-01",
      "is_demo": true
    }
  ],
  "products": [
    {
      "id": "demo-prod_1",
      "name": "Fil d'Élasthanne Premium GRS",
      "sku": "TX-EL-50-GRS",
      "category": "Produits Finis",
      "stockLevel": 1200,
      "minStockLevel": 500,
      "unitPrice": 24.5,
      "costPrice": 15.2,
      "supplierId": "sup_3",
      "supplierName": "Cotonière du Nord",
      "unit": "Kg",
      "createdDate": "2026-03-05",
      "is_demo": true
    },
    {
      "id": "demo-prod_2",
      "name": "Solvant d'Ethanol Purifié 99%",
      "sku": "CH-ET-99",
      "category": "Matières Premières",
      "stockLevel": 450,
      "minStockLevel": 600,
      "unitPrice": 8.8,
      "costPrice": 5.4,
      "supplierId": "sup_1",
      "supplierName": "Tunisie Chimie Industrielle (TCI)",
      "unit": "Litre",
      "createdDate": "2026-01-20",
      "is_demo": true
    },
    {
      "id": "demo-prod_3",
      "name": "Carton Ondulé Isolé Double Cannelure",
      "sku": "EM-CO-DC",
      "category": "Emballages",
      "stockLevel": 8500,
      "minStockLevel": 2000,
      "unitPrice": 1.25,
      "costPrice": 0.72,
      "supplierId": "sup_2",
      "supplierName": "Med Pack Sousse",
      "unit": "Pièce",
      "createdDate": "2026-02-15",
      "is_demo": true
    },
    {
      "id": "demo-prod_4",
      "name": "Fil de Coton Bio Peigné Ne 30/1",
      "sku": "TX-CO-30",
      "category": "Produits Finis",
      "stockLevel": 3200,
      "minStockLevel": 800,
      "unitPrice": 16.2,
      "costPrice": 10.1,
      "supplierId": "sup_3",
      "supplierName": "Cotonière du Nord",
      "unit": "Kg",
      "createdDate": "2026-03-12",
      "is_demo": true
    }
  ],
  "stockMovements": [
    {
      "id": "demo-mov_1",
      "productId": "prod_1",
      "productName": "Fil d'Élasthanne Premium GRS",
      "type": "In",
      "quantity": 1500,
      "date": "2026-06-01",
      "reference": "BC-2026-441 (Entrée Approvisionnement)",
      "operator": "Zied Ben Miled",
      "is_demo": true
    },
    {
      "id": "demo-mov_2",
      "productId": "prod_1",
      "productName": "Fil d'Élasthanne Premium GRS",
      "type": "Out",
      "quantity": 300,
      "date": "2026-06-10",
      "reference": "Livraison Client Sousse Textiles",
      "operator": "Karim Chahed",
      "is_demo": true
    },
    {
      "id": "demo-mov_3",
      "productId": "prod_2",
      "productName": "Solvant d'Ethanol Purifié 99%",
      "type": "Out",
      "quantity": 150,
      "date": "2026-06-12",
      "reference": "Prélèvement Ligne de Production B",
      "operator": "Sami Alouini",
      "is_demo": true
    },
    {
      "id": "demo-mov_4",
      "productId": "prod_3",
      "productName": "Carton Ondulé Isolé Double Cannelure",
      "type": "In",
      "quantity": 5000,
      "date": "2026-06-15",
      "reference": "Livraison Fournisseur Med Pack Sousse",
      "operator": "Hamdi Sraieb",
      "is_demo": true
    }
  ],
  "bankAccounts": [
    {
      "id": "demo-bank_biat",
      "bankName": "BIAT Tunis",
      "accountNumber": "TN59 0800 1234 5678 9012 3456",
      "type": "Checking",
      "initialBalance": 75000,
      "currentBalance": 75000,
      "currency": "TND",
      "status": "Active",
      "is_demo": true
    },
    {
      "id": "demo-bank_attijari",
      "bankName": "Attijari Bank Sfax",
      "accountNumber": "TN59 0400 9876 5432 1098 7654",
      "type": "Checking",
      "initialBalance": 42300.5,
      "currentBalance": 42300.5,
      "currency": "TND",
      "status": "Active",
      "is_demo": true
    },
    {
      "id": "demo-bank_uib_savings",
      "bankName": "UIB Compte d'Épargne",
      "accountNumber": "TN59 0300 1111 2222 3333 4444",
      "type": "Savings",
      "initialBalance": 120000,
      "currentBalance": 120000,
      "currency": "TND",
      "status": "Active",
      "is_demo": true
    },
    {
      "id": "demo-bank_caisse_cash",
      "bankName": "Caisse Principale (Espèces)",
      "accountNumber": "CAISSE-CD-TUNIS",
      "type": "CashBox",
      "initialBalance": 4850.25,
      "currentBalance": 4850.25,
      "currency": "TND",
      "status": "Active",
      "is_demo": true
    }
  ],
  "bankTransactions": [
    {
      "id": "demo-tx_001",
      "accountId": "bank_biat",
      "accountName": "BIAT Tunis",
      "date": "2026-06-01",
      "type": "In",
      "amount": 14500,
      "method": "Virement",
      "reference": "VIR-CLI-POULINA",
      "beneficiaryOrIssuer": "Poulina Group Holding",
      "category": "Vente",
      "description": "Règlement Facture FA-2026-001",
      "status": "Cleared",
      "is_demo": true
    },
    {
      "id": "demo-tx_002",
      "accountId": "bank_attijari",
      "accountName": "Attijari Bank Sfax",
      "date": "2026-06-05",
      "type": "In",
      "amount": 3200,
      "method": "Cheque",
      "reference": "CHQ-8827391",
      "dueDate": "2026-06-12",
      "beneficiaryOrIssuer": "Société El Majd",
      "category": "Vente",
      "description": "Chèque de caution ou d'acompte commande",
      "status": "Cleared",
      "is_demo": true
    },
    {
      "id": "demo-tx_003",
      "accountId": "bank_biat",
      "accountName": "BIAT Tunis",
      "date": "2026-06-08",
      "type": "Out",
      "amount": 8500.2,
      "method": "Traite",
      "reference": "TRT-FOURN-CHIMCO",
      "dueDate": "2026-06-28",
      "beneficiaryOrIssuer": "ChimCo Tunisie S.A.",
      "category": "Achat Fournisseur",
      "description": "Traite acceptée pour approvisionnement matières premières",
      "status": "Pending",
      "is_demo": true
    },
    {
      "id": "demo-tx_004",
      "accountId": "bank_caisse_cash",
      "accountName": "Caisse Principale (Espèces)",
      "date": "2026-06-10",
      "type": "Out",
      "amount": 180,
      "method": "Especes",
      "reference": "REC-CARBURANT",
      "beneficiaryOrIssuer": "Station Total Charguia",
      "category": "Autre",
      "description": "Frais de carburant camionnettes de livraison",
      "status": "Cleared",
      "is_demo": true
    },
    {
      "id": "demo-tx_005",
      "accountId": "bank_biat",
      "accountName": "BIAT Tunis",
      "date": "2026-06-12",
      "type": "Out",
      "amount": 2500,
      "method": "Virement",
      "reference": "LOY-2026-06",
      "beneficiaryOrIssuer": "SOPROT Tunis (Bailleur)",
      "category": "Loyer",
      "description": "Loyer mensuel bureaux Elyssa Distribution",
      "status": "Cleared",
      "is_demo": true
    },
    {
      "id": "demo-tx_006",
      "accountId": "bank_caisse_cash",
      "accountName": "Caisse Principale (Espèces)",
      "date": "2026-06-14",
      "type": "In",
      "amount": 450,
      "method": "Especes",
      "reference": "ESP-AL-ALOUA",
      "beneficiaryOrIssuer": "Épicerie Al Aloua",
      "category": "Vente",
      "description": "Paiement comptant livraison directe",
      "status": "Cleared",
      "is_demo": true
    },
    {
      "id": "demo-tx_007",
      "accountId": "bank_biat",
      "accountName": "BIAT Tunis",
      "date": "2026-06-15",
      "type": "Out",
      "amount": 14200,
      "method": "Virement",
      "reference": "SALAIRES-06-2026",
      "beneficiaryOrIssuer": "Personnel Elyssa Distribution (14 salariés)",
      "category": "Salaire",
      "description": "Virements de salaires du mois de Juin 2026",
      "status": "Cleared",
      "is_demo": true
    },
    {
      "id": "demo-tx_008",
      "accountId": "bank_attijari",
      "accountName": "Attijari Bank Sfax",
      "date": "2026-06-16",
      "type": "Out",
      "amount": 1250,
      "method": "Prelevement",
      "reference": "PRL-STEG-SF01",
      "beneficiaryOrIssuer": "STEG (Électricité)",
      "category": "Autre",
      "description": "Facture STEG trimestrielle dépôt Sfax",
      "status": "Cleared",
      "is_demo": true
    },
    {
      "id": "demo-tx_009",
      "accountId": "bank_biat",
      "accountName": "BIAT Tunis",
      "date": "2026-06-17",
      "type": "In",
      "amount": 9800,
      "method": "Traite",
      "reference": "TRT-CLI-MEDINA",
      "dueDate": "2026-07-15",
      "beneficiaryOrIssuer": "Supermarché Tunis Médina",
      "category": "Vente",
      "description": "Traite client tirée pour règlement facture FA-2026-004",
      "status": "Pending",
      "is_demo": true
    },
    {
      "id": "demo-tx_010",
      "accountId": "bank_biat",
      "accountName": "BIAT Tunis",
      "date": "2026-06-18",
      "type": "Out",
      "amount": 4500,
      "method": "Cheque",
      "reference": "CHQ-0027151",
      "dueDate": "2026-06-22",
      "beneficiaryOrIssuer": "Recette des Finances (Impôts)",
      "category": "Impôts & Taxes",
      "description": "Règlement déclaration fiscale mensuelle de Mai 2026",
      "status": "Cleared",
      "is_demo": true
    }
  ],
  "taxDeclarations": [
    {
      "id": "demo-tax_dec_01",
      "year": 2026,
      "period": "M01",
      "periodLabel": "Janvier 2026",
      "tvaCollected": 8540.3,
      "tvaDeductible": 5210.1,
      "tvaDue": 3330.2,
      "withholdingPaid": 650,
      "withholdingCollected": 420,
      "corporateTaxEstimate": 1450,
      "status": "Paid",
      "filedDate": "2026-02-25",
      "totalAmountPaid": 3100.2,
      "is_demo": true
    },
    {
      "id": "demo-tax_dec_02",
      "year": 2026,
      "period": "M02",
      "periodLabel": "Février 2026",
      "tvaCollected": 9430,
      "tvaDeductible": 6110,
      "tvaDue": 3320,
      "withholdingPaid": 710,
      "withholdingCollected": 510,
      "corporateTaxEstimate": 1620,
      "status": "Paid",
      "filedDate": "2026-03-25",
      "totalAmountPaid": 3120,
      "is_demo": true
    },
    {
      "id": "demo-tax_dec_03",
      "year": 2026,
      "period": "M03",
      "periodLabel": "Mars 2026",
      "tvaCollected": 12500.5,
      "tvaDeductible": 8400.2,
      "tvaDue": 4100.3,
      "withholdingPaid": 950,
      "withholdingCollected": 620,
      "corporateTaxEstimate": 2100,
      "status": "Paid",
      "filedDate": "2026-04-25",
      "totalAmountPaid": 3770.3,
      "is_demo": true
    },
    {
      "id": "demo-tax_dec_04",
      "year": 2026,
      "period": "M04",
      "periodLabel": "Avril 2026",
      "tvaCollected": 11200,
      "tvaDeductible": 7900,
      "tvaDue": 3300,
      "withholdingPaid": 840,
      "withholdingCollected": 580,
      "corporateTaxEstimate": 1950,
      "status": "Paid",
      "filedDate": "2026-05-25",
      "totalAmountPaid": 3040,
      "is_demo": true
    },
    {
      "id": "demo-tax_dec_05",
      "year": 2026,
      "period": "M05",
      "periodLabel": "Mai 2026",
      "tvaCollected": 14750,
      "tvaDeductible": 9150,
      "tvaDue": 5600,
      "withholdingPaid": 1100,
      "withholdingCollected": 750,
      "corporateTaxEstimate": 2500,
      "status": "Paid",
      "filedDate": "2026-06-18",
      "totalAmountPaid": 5250,
      "is_demo": true
    }
  ],
  "yearEndClosings": [
    {
      "id": "demo-cl_2024",
      "year": 2024,
      "closingDate": "2025-02-15",
      "closedBy": "Zied Ben Miled",
      "revenues": 1854000,
      "expenses": 1541000,
      "ebitda": 313000,
      "corporateTax": 46950,
      "netIncome": 266050,
      "status": "Closed",
      "notes": "Exercice 2024 finalisé et visé par le Commissaire aux Comptes. Quitus accordé.",
      "isLocked": true,
      "is_demo": true
    },
    {
      "id": "demo-cl_2025",
      "year": 2025,
      "closingDate": "2026-02-20",
      "closedBy": "Zied Ben Miled",
      "revenues": 2150000,
      "expenses": 1820000,
      "ebitda": 330000,
      "corporateTax": 49500,
      "netIncome": 280500,
      "status": "Closed",
      "notes": "Excédent brut d'exploitation en progression (+5.4%). Tous les comptes d'achats et de ventes sont formellement arrêtés et verouillés.",
      "isLocked": true,
      "is_demo": true
    },
    {
      "id": "demo-cl_2026",
      "year": 2026,
      "closingDate": "En attente",
      "closedBy": "",
      "revenues": 1245000,
      "expenses": 984500,
      "ebitda": 260500,
      "corporateTax": 39075,
      "netIncome": 221425,
      "status": "Draft",
      "notes": "Provisions en cours. Simulation financière mise à jour en temps réel à partir de la facturation et du journal.",
      "isLocked": false,
      "is_demo": true
    }
  ],
  "employees": [
    {
      "id": "EMP-LIV-01",
      "name": "Hamza Ben Salem",
      "email": "h.bensalem@elyssa-erp.tn",
      "phone": "+216 98 123 456",
      "jobTitle": "Chauffeur / Livreur Express",
      "department": "Logistique & Expéditions",
      "status": "Active",
      "contractType": "CDI",
      "baseSalary": 1450,
      "hiringDate": "2022-03-01",
      "ssn": "08765432-01",
      "assigned_module": "livraison",
      "is_demo": true
    },
    {
      "id": "EMP-COM-01",
      "name": "Sami Cherif",
      "email": "s.cherif@elyssa-erp.tn",
      "phone": "+216 97 234 567",
      "jobTitle": "Commercial Itinérant",
      "department": "Ventes & Commercial Terrain",
      "status": "Active",
      "contractType": "CDI",
      "baseSalary": 1850,
      "hiringDate": "2021-06-15",
      "ssn": "09876543-02",
      "assigned_module": "vente",
      "is_demo": true
    },
    {
      "id": "EMP-POS-01",
      "name": "Mounir Karray",
      "email": "m.karray@elyssa-erp.tn",
      "phone": "+216 95 345 678",
      "jobTitle": "Chef de Caisse / Vendeur POS",
      "department": "Magasin & Showroom POS",
      "status": "Active",
      "contractType": "CDI",
      "baseSalary": 1350,
      "hiringDate": "2023-01-10",
      "ssn": "07654321-03",
      "assigned_module": "vente",
      "is_demo": true
    },
    {
      "id": "demo-emp_1",
      "name": "Khaled Ben Amor (Démo)",
      "email": "k.benamor@carthage.com.tn",
      "jobTitle": "Directeur Financier & Recouvrement",
      "ssn": "14839211-92",
      "rib": "03001010015920038472",
      "baseSalary": 2600,
      "transportAllowance": 180,
      "presenceAllowance": 80,
      "otherAllowances": 300,
      "familySituation": "Married_2",
      "isChefDeFamille": true,
      "status": "Active",
      "hiringDate": "2023-01-15",
      "is_demo": true
    },
    {
      "id": "demo-emp_2",
      "name": "Ines Dridi (Démo)",
      "email": "i.dridi@carthage.com.tn",
      "jobTitle": "Responsable Rapprochement",
      "ssn": "20943810-18",
      "rib": "08102030026710048259",
      "baseSalary": 1750,
      "transportAllowance": 120,
      "presenceAllowance": 80,
      "otherAllowances": 150,
      "familySituation": "Single",
      "isChefDeFamille": false,
      "status": "Active",
      "hiringDate": "2024-03-10",
      "is_demo": true
    },
    {
      "id": "demo-emp_3",
      "name": "Mohamed Ali Gharbi (Démo)",
      "email": "m.gharbi@carthage.com.tn",
      "jobTitle": "Chargé Clientèle Extérieure",
      "ssn": "12554739-44",
      "rib": "12004050037840059341",
      "baseSalary": 1400,
      "transportAllowance": 110,
      "presenceAllowance": 80,
      "otherAllowances": 100,
      "familySituation": "Married_1",
      "isChefDeFamille": true,
      "status": "Active",
      "hiringDate": "2025-06-18",
      "is_demo": true
    },
    {
      "id": "demo-emp_4",
      "name": "Amel Ben Soltane (Démo)",
      "email": "a.bensoltane@carthage.com.tn",
      "jobTitle": "Responsable Ressources Humaines",
      "ssn": "19483029-45",
      "rib": "05201040059283749501",
      "baseSalary": 2100,
      "transportAllowance": 150,
      "presenceAllowance": 80,
      "otherAllowances": 200,
      "familySituation": "Married_3",
      "isChefDeFamille": true,
      "status": "Active",
      "hiringDate": "2024-11-01",
      "is_demo": true
    },
    {
      "id": "demo-emp_5",
      "name": "Sami Mansour (Démo)",
      "email": "s.mansour@carthage.com.tn",
      "jobTitle": "Développeur ERP Principal",
      "ssn": "11049382-77",
      "rib": "14102030048592837410",
      "baseSalary": 3200,
      "transportAllowance": 200,
      "presenceAllowance": 80,
      "otherAllowances": 500,
      "familySituation": "Single",
      "isChefDeFamille": false,
      "status": "Active",
      "hiringDate": "2025-01-10",
      "is_demo": true
    }
  ],
  "contracts": [
    {
      "id": "demo-ct_1",
      "employeeId": "demo-emp_1",
      "employeeName": "Khaled Ben Amor (Démo)",
      "contractType": "CDI",
      "startDate": "2023-01-15",
      "trialPeriodMonths": 3,
      "baseSalary": 2600,
      "status": "Signed",
      "dutiesDescription": "Superviser l'ensemble des processus financiers, élaboration du budget annuel, pilotage de la trésorerie et reporting réglementaire de Elyssa S.A. auprès de la Banque Centrale de Tunisie.",
      "generatedAt": "2023-01-15",
      "signedAt": "2023-01-15",
      "is_demo": true
    },
    {
      "id": "demo-ct_2",
      "employeeId": "demo-emp_2",
      "employeeName": "Ines Dridi (Démo)",
      "contractType": "CDD",
      "startDate": "2024-03-10",
      "endDate": "2026-03-09",
      "trialPeriodMonths": 2,
      "baseSalary": 1750,
      "status": "Signed",
      "dutiesDescription": "Contrôler les opérations de rapprochement bancaire, auditer les pièces comptables de paie et s'assurer du respect des règles fiscales de retenue à la source en Tunisie.",
      "generatedAt": "2024-03-05",
      "signedAt": "2024-03-10",
      "is_demo": true
    },
    {
      "id": "demo-ct_3",
      "employeeId": "demo-emp_3",
      "employeeName": "Mohamed Ali Gharbi (Démo)",
      "contractType": "CIVP",
      "startDate": "2025-06-18",
      "endDate": "2026-06-17",
      "trialPeriodMonths": 1,
      "baseSalary": 1400,
      "status": "Signed",
      "dutiesDescription": "Assister les clients de Elyssa S.A., préparer la documentation de prospection commerciale et de service extérieur pour la zone industrielle de Charguia et Ben Arous.",
      "generatedAt": "2025-06-15",
      "signedAt": "2025-06-18",
      "is_demo": true
    },
    {
      "id": "demo-ct_4",
      "employeeId": "demo-emp_4",
      "employeeName": "Amel Ben Soltane (Démo)",
      "contractType": "CDI",
      "startDate": "2024-11-01",
      "trialPeriodMonths": 3,
      "baseSalary": 2100,
      "status": "Signed",
      "dutiesDescription": "Gérer l'ensemble des dossiers administratifs du personnel, l'élaboration de la paie mensuelle, le suivi des recrutements et des relations avec la CNSS et l'Inspection du Travail.",
      "generatedAt": "2024-10-25",
      "signedAt": "2024-11-01",
      "is_demo": true
    },
    {
      "id": "demo-ct_5",
      "employeeId": "demo-emp_5",
      "employeeName": "Sami Mansour (Démo)",
      "contractType": "CDI",
      "startDate": "2025-01-10",
      "trialPeriodMonths": 3,
      "baseSalary": 3200,
      "status": "Signed",
      "dutiesDescription": "Concevoir et développer de nouveaux modules logiciels pour l'ERP Elyssa, assurer la maintenance corrective et évolutive des applications, et optimiser les performances de la base de données.",
      "generatedAt": "2025-01-05",
      "signedAt": "2025-01-10",
      "is_demo": true
    }
  ],
  "absences": [
    {
      "id": "demo-abs_1",
      "employeeId": "demo-emp_2",
      "employeeName": "Ines Dridi (Démo)",
      "type": "SickLeave",
      "startDate": "2026-06-02",
      "endDate": "2026-06-05",
      "daysCount": 4,
      "isDeductibleFromSalary": true,
      "deductionAmount": 240,
      "status": "Approved",
      "description": "Grippe saisonnière sévère - Certificat médical transmis",
      "is_demo": true
    },
    {
      "id": "demo-abs_2",
      "employeeId": "demo-emp_3",
      "employeeName": "Mohamed Ali Gharbi (Démo)",
      "type": "WorkAccident",
      "startDate": "2026-06-10",
      "endDate": "2026-06-12",
      "daysCount": 3,
      "isDeductibleFromSalary": false,
      "deductionAmount": 0,
      "status": "Approved",
      "description": "Accident de trajet (visite clientèle) - Notification d'arrêt délivrée par la CNAM",
      "is_demo": true
    },
    {
      "id": "demo-abs_3",
      "employeeId": "demo-emp_1",
      "employeeName": "Khaled Ben Amor (Démo)",
      "type": "PaidLeave",
      "startDate": "2026-06-15",
      "endDate": "2026-06-19",
      "daysCount": 5,
      "isDeductibleFromSalary": false,
      "deductionAmount": 0,
      "status": "Approved",
      "description": "Congés d'été annuels validés par la Direction",
      "is_demo": true
    }
  ],
  "payslips": [
    {
      "id": "demo-ps_1_may",
      "employeeId": "demo-emp_1",
      "employeeName": "Khaled Ben Amor (Démo)",
      "month": "2026-05",
      "baseSalary": 2600,
      "grossSalary": 3160,
      "cnssEmployee": 290.088,
      "cnssEmployer": 539.412,
      "professionalExpenses": 166.667,
      "familyDeduction": 41.667,
      "taxableIncome": 2661.578,
      "irpp": 582.345,
      "css": 26.616,
      "netSalary": 2260.951,
      "allowancesPaid": 560,
      "status": "Paid",
      "paymentMethod": "Virement",
      "bankAccountId": "ba_1",
      "paidDate": "2026-05-31",
      "is_demo": true
    },
    {
      "id": "demo-ps_2_may",
      "employeeId": "demo-emp_2",
      "employeeName": "Ines Dridi (Démo)",
      "month": "2026-05",
      "baseSalary": 1750,
      "grossSalary": 2100,
      "cnssEmployee": 192.78,
      "cnssEmployer": 358.47,
      "professionalExpenses": 166.667,
      "familyDeduction": 0,
      "taxableIncome": 1740.553,
      "irpp": 312.45,
      "css": 17.406,
      "netSalary": 1577.364,
      "allowancesPaid": 350,
      "status": "Paid",
      "paymentMethod": "Virement",
      "bankAccountId": "ba_1",
      "paidDate": "2026-05-31",
      "is_demo": true
    },
    {
      "id": "demo-ps_3_may",
      "employeeId": "demo-emp_3",
      "employeeName": "Mohamed Ali Gharbi (Démo)",
      "month": "2026-05",
      "baseSalary": 1400,
      "grossSalary": 1690,
      "cnssEmployee": 155.142,
      "cnssEmployer": 288.483,
      "professionalExpenses": 153.486,
      "familyDeduction": 33.333,
      "taxableIncome": 1348.039,
      "irpp": 202.15,
      "css": 13.48,
      "netSalary": 1319.228,
      "allowancesPaid": 290,
      "status": "Paid",
      "paymentMethod": "Virement",
      "bankAccountId": "ba_1",
      "paidDate": "2026-05-31",
      "is_demo": true
    },
    {
      "id": "demo-ps_4_may",
      "employeeId": "demo-emp_4",
      "employeeName": "Amel Ben Soltane (Démo)",
      "month": "2026-05",
      "baseSalary": 2100,
      "grossSalary": 2530,
      "cnssEmployee": 232.254,
      "cnssEmployer": 431.871,
      "professionalExpenses": 166.667,
      "familyDeduction": 50,
      "taxableIncome": 2081.079,
      "irpp": 412.35,
      "css": 20.811,
      "netSalary": 1864.585,
      "allowancesPaid": 430,
      "status": "Paid",
      "paymentMethod": "Virement",
      "bankAccountId": "ba_1",
      "paidDate": "2026-05-31",
      "is_demo": true
    },
    {
      "id": "demo-ps_5_may",
      "employeeId": "demo-emp_5",
      "employeeName": "Sami Mansour (Démo)",
      "month": "2026-05",
      "baseSalary": 3200,
      "grossSalary": 3980,
      "cnssEmployee": 365.364,
      "cnssEmployer": 679.386,
      "professionalExpenses": 166.667,
      "familyDeduction": 0,
      "taxableIncome": 3447.969,
      "irpp": 825.4,
      "css": 34.48,
      "netSalary": 2754.756,
      "allowancesPaid": 780,
      "status": "Paid",
      "paymentMethod": "Virement",
      "bankAccountId": "ba_1",
      "paidDate": "2026-05-31",
      "is_demo": true
    },
    {
      "id": "demo-ps_1_june",
      "employeeId": "demo-emp_1",
      "employeeName": "Khaled Ben Amor (Démo)",
      "month": "2026-06",
      "baseSalary": 2600,
      "grossSalary": 3160,
      "cnssEmployee": 290.088,
      "cnssEmployer": 539.412,
      "professionalExpenses": 166.667,
      "familyDeduction": 41.667,
      "taxableIncome": 2661.578,
      "irpp": 582.345,
      "css": 26.616,
      "netSalary": 2260.951,
      "allowancesPaid": 560,
      "status": "Approved",
      "paymentMethod": "Virement",
      "bankAccountId": "ba_1",
      "is_demo": true
    },
    {
      "id": "demo-ps_2_june",
      "employeeId": "demo-emp_2",
      "employeeName": "Ines Dridi (Démo)",
      "month": "2026-06",
      "baseSalary": 1750,
      "grossSalary": 1860,
      "cnssEmployee": 170.748,
      "cnssEmployer": 317.502,
      "professionalExpenses": 155.333,
      "familyDeduction": 0,
      "taxableIncome": 1533.919,
      "irpp": 252.35,
      "css": 15.339,
      "netSalary": 1421.563,
      "allowancesPaid": 350,
      "absencesDeduction": 240,
      "absenceDaysTracked": 4,
      "status": "Approved",
      "paymentMethod": "Virement",
      "bankAccountId": "ba_1",
      "is_demo": true
    },
    {
      "id": "demo-ps_3_june",
      "employeeId": "demo-emp_3",
      "employeeName": "Mohamed Ali Gharbi (Démo)",
      "month": "2026-06",
      "baseSalary": 1400,
      "grossSalary": 1690,
      "cnssEmployee": 155.142,
      "cnssEmployer": 288.483,
      "professionalExpenses": 153.486,
      "familyDeduction": 33.333,
      "taxableIncome": 1348.039,
      "irpp": 202.15,
      "css": 13.48,
      "netSalary": 1319.228,
      "allowancesPaid": 290,
      "status": "Draft",
      "paymentMethod": "Virement",
      "bankAccountId": "ba_1",
      "is_demo": true
    }
  ],
  "documents": [
    {
      "id": "demo-doc_1",
      "name": "Contrat_CDI_Khaled_Ben_Amor_Signed",
      "type": "Contract",
      "fileSize": "245 KB",
      "fileType": "application/pdf",
      "uploadDate": "2023-01-15",
      "linkedToType": "Employee",
      "linkedToId": "demo-emp_1",
      "linkedToName": "Khaled Ben Amor (Démo)",
      "description": "Contrat de travail permanent en qualité de Directeur Financier & Recouvrement.",
      "version": 1,
      "uploadedBy": "contact@elyssa.pro",
      "is_demo": true
    },
    {
      "id": "demo-doc_2",
      "name": "Attestation_Ines_Dridi_ID",
      "type": "Other",
      "fileSize": "112 KB",
      "fileType": "image/png",
      "uploadDate": "2024-03-10",
      "linkedToType": "Employee",
      "linkedToId": "demo-emp_2",
      "linkedToName": "Ines Dridi (Démo)",
      "description": "Copie scannée de la Carte d'Identité Nationale (CIN).",
      "version": 1,
      "uploadedBy": "contact@elyssa.pro",
      "is_demo": true
    },
    {
      "id": "demo-doc_3",
      "name": "Contrat_CIVP_Mohamed_Ali_Gharbi_Signed",
      "type": "Contract",
      "fileSize": "185 KB",
      "fileType": "application/pdf",
      "uploadDate": "2025-06-18",
      "linkedToType": "Employee",
      "linkedToId": "demo-emp_3",
      "linkedToName": "Mohamed Ali Gharbi (Démo)",
      "description": "Contrat d'insertion CIVP visé par l'ANETI.",
      "version": 1,
      "uploadedBy": "contact@elyssa.pro",
      "is_demo": true
    },
    {
      "id": "demo-doc_4",
      "name": "Fiche_Paie_Khaled_Ben_Amor_Mai_2026",
      "type": "Other",
      "fileSize": "85 KB",
      "fileType": "application/pdf",
      "uploadDate": "2026-05-31",
      "linkedToType": "Employee",
      "linkedToId": "demo-emp_1",
      "linkedToName": "Khaled Ben Amor (Démo)",
      "description": "Fiche de paie numérique certifiée conforme pour Mai 2026.",
      "version": 1,
      "uploadedBy": "contact@elyssa.pro",
      "is_demo": true
    }
  ],
  "importFolders": [
    {
      "id": "demo-imp_1",
      "reference": "IMP-2026-001 (Démo)",
      "folderType": "Import",
      "supplierName": "Marseille Chimie SAS",
      "originCountry": "France",
      "incoterm": "FOB",
      "portOfArrival": "Radès",
      "transitterName": "Société Tunisienne de Transit & Logistique (STTL)",
      "status": "Customs",
      "creationDate": "2026-06-01",
      "estimatedArrivalDate": "2026-06-30",
      "currency": "EUR",
      "exchangeRate": 3.42,
      "items": [
        {
          "id": "demo-item_1",
          "productName": "Solvant Éco Purifié",
          "quantity": 1500,
          "fobUnitPrice": 4.5,
          "foreignCurrencyRate": 3.42,
          "customsDutyRate": 15,
          "vatRate": 19,
          "is_demo": true
        },
        {
          "id": "demo-item_2",
          "productName": "Additif Stabilisateur X20",
          "quantity": 800,
          "fobUnitPrice": 12,
          "foreignCurrencyRate": 3.42,
          "customsDutyRate": 10,
          "vatRate": 19,
          "is_demo": true
        }
      ],
      "freightCostTND": 4200,
      "customsDutiesTND": 8150,
      "transitterFeesTND": 1200,
      "handlingFeesTND": 850,
      "insuranceCostTND": 650,
      "otherFeesTND": 300,
      "is_demo": true
    },
    {
      "id": "demo-imp_2",
      "reference": "IMP-2026-002 (Démo)",
      "folderType": "Import",
      "supplierName": "Genoa Industrial Valves",
      "originCountry": "Italie",
      "incoterm": "EXW",
      "portOfArrival": "Radès",
      "transitterName": "Société Tunisienne de Transit & Logistique (STTL)",
      "status": "Transport",
      "creationDate": "2026-06-10",
      "estimatedArrivalDate": "2026-07-05",
      "currency": "EUR",
      "exchangeRate": 3.42,
      "items": [
        {
          "id": "demo-item_3",
          "productName": "Vanne Haute Pression V3",
          "quantity": 120,
          "fobUnitPrice": 85,
          "foreignCurrencyRate": 3.42,
          "customsDutyRate": 20,
          "vatRate": 19,
          "is_demo": true
        },
        {
          "id": "demo-item_4",
          "productName": "Joint Torique Graphene",
          "quantity": 2000,
          "fobUnitPrice": 1.2,
          "foreignCurrencyRate": 3.42,
          "customsDutyRate": 5,
          "vatRate": 19,
          "is_demo": true
        }
      ],
      "freightCostTND": 3500,
      "customsDutiesTND": 12400,
      "transitterFeesTND": 1000,
      "handlingFeesTND": 600,
      "insuranceCostTND": 450,
      "otherFeesTND": 150,
      "is_demo": true
    },
    {
      "id": "demo-imp_3",
      "reference": "IMP-2026-003 (Démo)",
      "folderType": "Import",
      "supplierName": "Istanbul Petrochemicals",
      "originCountry": "Turquie",
      "incoterm": "CIF",
      "portOfArrival": "Radès",
      "transitterName": "Société Tunisienne de Transit & Logistique (STTL)",
      "status": "Pending",
      "creationDate": "2026-06-18",
      "estimatedArrivalDate": "2026-07-15",
      "currency": "USD",
      "exchangeRate": 3.12,
      "items": [
        {
          "id": "demo-item_5",
          "productName": "Résine Synthétique Premium",
          "quantity": 5000,
          "fobUnitPrice": 2.1,
          "foreignCurrencyRate": 3.12,
          "customsDutyRate": 15,
          "vatRate": 19,
          "is_demo": true
        }
      ],
      "freightCostTND": 6200,
      "customsDutiesTND": 11450,
      "transitterFeesTND": 1500,
      "handlingFeesTND": 900,
      "insuranceCostTND": 800,
      "otherFeesTND": 400,
      "is_demo": true
    },
    {
      "id": "demo-exp_1",
      "reference": "EXP-2026-001 (Démo)",
      "folderType": "Export",
      "supplierName": "Marseille Chimie SAS",
      "originCountry": "France",
      "incoterm": "FOB",
      "portOfArrival": "Radès",
      "transitterName": "Société Tunisienne de Transit & Logistique (STTL)",
      "status": "Customs",
      "creationDate": "2026-06-01",
      "estimatedArrivalDate": "2026-06-30",
      "currency": "EUR",
      "exchangeRate": 3.42,
      "items": [
        {
          "id": "demo-exp-item_1",
          "productName": "Résine Polyéthylène Haute Densité (PEHD)",
          "quantity": 4000,
          "fobUnitPrice": 1.8,
          "foreignCurrencyRate": 3.12,
          "customsDutyRate": 0,
          "vatRate": 0,
          "is_demo": true
        }
      ],
      "freightCostTND": 2200,
      "customsDutiesTND": 0,
      "transitterFeesTND": 1000,
      "handlingFeesTND": 500,
      "insuranceCostTND": 350,
      "otherFeesTND": 100,
      "is_demo": true
    },
    {
      "id": "demo-exp_2",
      "reference": "EXP-2026-002 (Démo)",
      "folderType": "Export",
      "supplierName": "Genoa Industrial Valves",
      "originCountry": "Italie",
      "incoterm": "EXW",
      "portOfArrival": "Radès",
      "transitterName": "Société Tunisienne de Transit & Logistique (STTL)",
      "status": "Transport",
      "creationDate": "2026-06-10",
      "estimatedArrivalDate": "2026-07-05",
      "currency": "EUR",
      "exchangeRate": 3.42,
      "items": [
        {
          "id": "demo-exp-item_2",
          "productName": "Adjuvants Ciment Spécifiques",
          "quantity": 12000,
          "fobUnitPrice": 0.95,
          "foreignCurrencyRate": 3.42,
          "customsDutyRate": 0,
          "vatRate": 0,
          "is_demo": true
        }
      ],
      "freightCostTND": 2500,
      "customsDutiesTND": 0,
      "transitterFeesTND": 1000,
      "handlingFeesTND": 500,
      "insuranceCostTND": 400,
      "otherFeesTND": 200,
      "is_demo": true
    }
  ],
  "lcRequests": [
    {
      "id": "demo-lc_1",
      "importFolderId": "demo-imp_1",
      "folderType": "Import",
      "lcReference": "BIAT-CDOC-2026-0819 (Démo)",
      "proformaInvoiceRef": "PROFORMA-MC-1029",
      "proformaInvoiceDate": "2026-05-25",
      "issuingBank": "Banque Internationale Arabe de Tunisie (BIAT) - Agence Sfax El Jadida",
      "beneficiaryName": "Marseille Chimie SAS",
      "beneficiaryAddress": "Avenue de l'Exportation, Zone Portuaire, 13002 Marseille, France",
      "advisingBank": "BNP Paribas - Agence Marseille Joliette",
      "amount": 16350,
      "currency": "EUR",
      "paymentTerms": "At Sight",
      "expiryDate": "2026-08-30",
      "shipmentDeadline": "2026-06-30",
      "portOfLoading": "Port de Marseille, France",
      "portOfDischarge": "Port de Radès, Tunisie",
      "status": "Issued",
      "amendments": [],
      "requiredDocuments": [
        "Commercial Invoice (3 copies)",
        "Full set of clean on board Bill of Lading, marked Freight Prepaid",
        "Certificate of Origin",
        "Analysis Certificate for chemical solvents"
      ],
      "comments": "Crédit documentaire irrévocable et confirmé par BNP Paribas. Émission rapide validée par le DAF.",
      "is_demo": true
    },
    {
      "id": "demo-lc_2",
      "importFolderId": "demo-imp_2",
      "folderType": "Import",
      "lcReference": "BIAT-CDOC-2026-0941 (Démo)",
      "proformaInvoiceRef": "PROFORMA-GIV-4822",
      "proformaInvoiceDate": "2026-06-05",
      "issuingBank": "Banque Internationale Arabe de Tunisie (BIAT) - Agence Sfax El Jadida",
      "beneficiaryName": "Genoa Industrial Valves",
      "beneficiaryAddress": "Via della Logistica, Block C, 16121 Gênes, Italie",
      "advisingBank": "UniCredit Spa - Agence Gênes Port",
      "amount": 12600,
      "currency": "EUR",
      "paymentTerms": "30 Days End of Month",
      "expiryDate": "2026-09-15",
      "shipmentDeadline": "2026-07-05",
      "portOfLoading": "Port de Gênes, Italie",
      "portOfDischarge": "Port de Radès, Tunisie",
      "status": "Approved",
      "amendments": [],
      "requiredDocuments": [
        "Commercial Invoice (2 copies)",
        "Packing List",
        "Bill of Lading",
        "EUR.1 Certificate"
      ],
      "comments": "En attente de transmission à la banque correspondante en Italie.",
      "is_demo": true
    },
    {
      "id": "demo-lc_export_1",
      "importFolderId": "demo-exp_1",
      "folderType": "Export",
      "lcReference": "SG-CDOC-2026-0033 (Démo)",
      "proformaInvoiceRef": "EXP-PROFORMA-001",
      "proformaInvoiceDate": "2026-05-20",
      "issuingBank": "Société Générale - Agence Marseille Joliette",
      "beneficiaryName": "Marseille Chimie SAS",
      "beneficiaryAddress": "Avenue de l'Exportation, Zone Portuaire, 13002 Marseille, France",
      "advisingBank": "BNP Paribas - Agence Marseille Joliette",
      "amount": 7200,
      "currency": "EUR",
      "paymentTerms": "At Sight",
      "expiryDate": "2026-08-30",
      "shipmentDeadline": "2026-06-30",
      "portOfLoading": "Port de Marseille, France",
      "portOfDischarge": "Port de Radès, Tunisie",
      "status": "Issued",
      "amendments": [],
      "requiredDocuments": [
        "Commercial Invoice (3 copies)",
        "Full set of clean on board Bill of Lading, marked Freight Prepaid",
        "Certificate of Origin"
      ],
      "comments": "Crédit documentaire irrévocable et de qualité.",
      "is_demo": true
    }
  ],
  "vehicles": [
    {
      "id": "FLEET-ISUZU-01",
      "brand": "Isuzu",
      "model": "D-Max",
      "registrationNumber": "TN-210-9842",
      "serial_reference": "TN-210-9842",
      "fleet_park": "Dépôt Central Charguia",
      "category": "Véhicule Utilitaire / Camion",
      "status": "Available",
      "assignedDriver": "Hamza Ben Salem",
      "is_demo": true
    },
    {
      "id": "FLEET-PARTNER-02",
      "brand": "Peugeot",
      "model": "Partner",
      "registrationNumber": "TN-198-4431",
      "serial_reference": "TN-198-4431",
      "fleet_park": "Magasin Principal Tunis",
      "category": "Véhicule Utilitaire",
      "status": "Available",
      "assignedDriver": "Sami Cherif",
      "is_demo": true
    },
    {
      "id": "demo-v_1",
      "brand": "Peugeot",
      "model": "Partner",
      "registrationNumber": "228 TUN 4091",
      "purchaseDate": "2024-03-12",
      "purchasePrice": 62000,
      "status": "Active",
      "is_demo": true
    },
    {
      "id": "demo-v_2",
      "brand": "Isuzu",
      "model": "D-Max",
      "registrationNumber": "215 TUN 9832",
      "purchaseDate": "2023-08-18",
      "purchasePrice": 89000,
      "status": "Active",
      "is_demo": true
    },
    {
      "id": "demo-v_3",
      "brand": "Citroën",
      "model": "C-Élysée",
      "registrationNumber": "241 TUN 1109",
      "purchaseDate": "2025-01-20",
      "purchasePrice": 54000,
      "status": "Active",
      "is_demo": true
    }
  ],
  "fuelBons": [
    {
      "id": "demo-exp_1",
      "date": "2026-06-02",
      "vehicleId": "demo-v_1",
      "vehicleLabel": "Peugeot Partner (228 TUN 4091) (Démo)",
      "category": "GasolineBonus",
      "amount": 120,
      "invoiceNb": "BON_OLA_39912",
      "providerName": "Ola Energy Charguia",
      "description": "Recharge carte carburant mensuelle",
      "is_demo": true
    }
  ],
  "interventions": [
    {
      "id": "demo-it_1",
      "vehicleId": "demo-v_1",
      "type": "Vidange",
      "date": "2026-05-10",
      "cost": 140,
      "description": "Changement filtre à huile et filtre à air - Huile 10W40 5L chez Agil Sfax.",
      "provider": "Agil Sfax Service",
      "status": "Completed",
      "is_demo": true
    },
    {
      "id": "demo-it_2",
      "vehicleId": "demo-v_2",
      "type": "Reparation",
      "date": "2026-05-24",
      "cost": 480,
      "description": "Remplacement plaquettes de frein avant et disque de frein droit chez Isuzu Tunis.",
      "provider": "Isuzu Tunisie - Sousse",
      "status": "Completed",
      "is_demo": true
    }
  ],
  "insurances": [
    {
      "id": "demo-ins_1",
      "vehicleId": "demo-v_1",
      "provider": "GAT Assurances",
      "policyNumber": "POL-GAT-90812",
      "startDate": "2026-03-12",
      "endDate": "2027-03-11",
      "annualCost": 1120,
      "status": "Active",
      "is_demo": true
    },
    {
      "id": "demo-ins_2",
      "vehicleId": "demo-v_2",
      "provider": "Star Assurances",
      "policyNumber": "POL-STAR-74892",
      "startDate": "2025-08-18",
      "endDate": "2026-08-17",
      "annualCost": 1450,
      "status": "Active",
      "is_demo": true
    }
  ],
  "assets": [
    {
      "id": "demo-IMM-2024-001",
      "name": "Extrudeuse Industrielle Haute Fréquence PEHD",
      "category": "Matériel Industriel",
      "purchaseDate": "2024-01-15",
      "initialValue": 185000,
      "usefulLifeYears": 10,
      "scrapValue": 0,
      "amortizationType": "Linéaire",
      "location": "Usine de Sfax",
      "is_demo": true
    },
    {
      "id": "demo-IMM-2025-001",
      "name": "Serveurs Rack Core i9 Datacenter Tunis",
      "category": "Matériel Informatique",
      "purchaseDate": "2025-03-10",
      "initialValue": 24000,
      "usefulLifeYears": 3,
      "scrapValue": 0,
      "amortizationType": "Linéaire",
      "location": "Siège Social Tunis",
      "is_demo": true
    },
    {
      "id": "demo-IMM-2024-002",
      "name": "Camion de Livraison Isotherme Isuzu 3.5T",
      "category": "Matériel de Transport",
      "purchaseDate": "2024-06-20",
      "initialValue": 85000,
      "usefulLifeYears": 5,
      "scrapValue": 0,
      "amortizationType": "Linéaire",
      "location": "Dépôt de Sousse",
      "is_demo": true
    }
  ],
  "cessionEntries": [
    {
      "id": "demo-cess-1",
      "date": "2026-06-15",
      "time": "09:30",
      "title": "Audit initial & Évaluation d'Entreprise",
      "category": "Evaluation",
      "direction": "Direction Financière",
      "authorName": "Khaled Ben Amor",
      "authorRole": "Dirigeant",
      "financialImpact": 4500000,
      "description": "Rapport d'évaluation d'actifs corporels et incorporels élaboré par notre Expert-Comptable agréé par l'OECT. La valeur de cession conseillée est arrêtée entre 4,2 MD et 4,8 MD.",
      "status": "Approuvé",
      "attachmentsCount": 3,
      "is_demo": true
    },
    {
      "id": "demo-cess-2",
      "date": "2026-06-18",
      "time": "14:15",
      "title": "Audit de conformité sociale - Article 15 du Code du Travail",
      "category": "Ressources Humaines",
      "direction": "Direction RH",
      "authorName": "Sonia Meriah",
      "authorRole": "Collaborateur",
      "financialImpact": 0,
      "description": "Vérification de la validité de l'ancienneté et des contrats des 42 salariés. En vertu de l'article 15 du Code du Travail tunisien, tous les contrats de travail en cours seront maintenus automatiquement chez le repreneur.",
      "status": "Complété",
      "attachmentsCount": 1,
      "is_demo": true
    },
    {
      "id": "demo-cess-3",
      "date": "2026-06-20",
      "time": "11:00",
      "title": "Calcul prévisionnel d'impôt sur la plus-value de cession",
      "category": "Fiscal",
      "direction": "Direction Financière",
      "authorName": "Mohamed Ali Gharbi",
      "authorRole": "Collaborateur",
      "financialImpact": -112500,
      "description": "Estimation de l'impôt sur les plus-values professionnelles de cession d'actions ordinaires. Réintégration au résultat fiscal imposable à hauteur du taux standard tunisien de 15%. Plus-value estimée à 750 000 TND, d'où un impôt latent de 112 500 TND.",
      "status": "Soumis",
      "attachmentsCount": 2,
      "is_demo": true
    },
    {
      "id": "demo-cess-4",
      "date": "2026-06-22",
      "time": "16:00",
      "title": "Rédaction du compromis de vente (Lettre d'Intention - LOI)",
      "category": "Juridique",
      "direction": "Direction Juridique",
      "authorName": "Emna Kallel",
      "authorRole": "Dirigeant",
      "financialImpact": 0,
      "description": "Validation de l'avant-projet de compromis de cession avec clause de confidentialité stricte (\"NDA\") et période d'exclusivité de 60 jours négociée avec l'acquéreur (Holding El-Qarawan).",
      "status": "Approuvé",
      "attachmentsCount": 4,
      "is_demo": true
    },
    {
      "id": "demo-cess-5",
      "date": "2026-06-25",
      "time": "10:30",
      "title": "Négociation du prix de cession & Garanties d'Actifs et de Passifs",
      "category": "Négociation",
      "direction": "Direction Générale",
      "authorName": "Zied Ben Miled",
      "authorRole": "Dirigeant",
      "financialImpact": 4650000,
      "description": "Séance finale de négociation de la GAP (Garantie d'Actif et de Passif). L'acheteur accepte une valorisation finale de 4 650 000 TND avec un compte séquestre de 10% dans une banque tunisienne pour couvrir les passifs éventuels non déclarés.",
      "status": "Soumis",
      "attachmentsCount": 1,
      "is_demo": true
    },
    {
      "id": "demo-cess-6",
      "date": "2026-06-28",
      "time": "09:00",
      "title": "Inventaire contradictoire des stocks physiques",
      "category": "Audit",
      "direction": "Direction Technique",
      "authorName": "Tarek Chaabane",
      "authorRole": "Collaborateur",
      "financialImpact": 280000,
      "description": "Saisie de l'inventaire physique contradictoire des stocks d'intrants et de produits finis aux entrepôts de la Charguia 2 et Sousse. La valorisation nette d'inventaire est conforme aux écritures comptables à 98.7%.",
      "status": "Brouillon",
      "attachmentsCount": 0,
      "is_demo": true
    },
    {
      "id": "demo-cess-7",
      "date": "2026-06-29",
      "time": "08:45",
      "title": "Déclaration préalable de cession au bureau d'enregistrement",
      "category": "Fiscal",
      "direction": "Direction Juridique",
      "authorName": "Rim Oueslati",
      "authorRole": "Collaborateur",
      "financialImpact": -15000,
      "description": "Enregistrement de l'acte de cession au bureau de la Recette des Finances. Droits d'enregistrement fixes à 150 TND par acte et taxation proportionnelle selon le type d'apport le cas échéant.",
      "status": "Complété",
      "attachmentsCount": 1,
      "is_demo": true
    }
  ],
  "nomenclatures": [
    {
      "id": "demo-nom-1",
      "productName": "Câble Électrique Isolé 2.5mm²",
      "category": "Câblerie & Électricité",
      "estimatedTimeMinutes": 12,
      "laborCostPerUnit": 1.2,
      "materials": [
        {
          "id": "m1",
          "name": "Cuivre Cathodique Pur",
          "quantityNeeded": 0.18,
          "unit": "kg",
          "unitCost": 24.5
        },
        {
          "id": "m2",
          "name": "Grains PVC Isolants (Gris)",
          "quantityNeeded": 0.12,
          "unit": "kg",
          "unitCost": 4.8
        },
        {
          "id": "m3",
          "name": "Touret Bois de Conditionnement",
          "quantityNeeded": 0.01,
          "unit": "u",
          "unitCost": 15
        }
      ],
      "is_demo": true
    },
    {
      "id": "demo-nom-2",
      "productName": "Disjoncteur Divisionnaire 16A",
      "category": "Appareillage Électrique",
      "estimatedTimeMinutes": 25,
      "laborCostPerUnit": 2.5,
      "materials": [
        {
          "id": "m4",
          "name": "Ressort Acier Allié",
          "quantityNeeded": 1,
          "unit": "u",
          "unitCost": 0.35
        },
        {
          "id": "m5",
          "name": "Boîtier Plastique Auto-extinguible",
          "quantityNeeded": 1,
          "unit": "u",
          "unitCost": 1.1
        },
        {
          "id": "m6",
          "name": "Bandes de Cuivre de Contact",
          "quantityNeeded": 0.05,
          "unit": "kg",
          "unitCost": 26
        },
        {
          "id": "m7",
          "name": "Bobine de Déclenchement Magnétique",
          "quantityNeeded": 1,
          "unit": "u",
          "unitCost": 1.8
        }
      ],
      "is_demo": true
    },
    {
      "id": "demo-nom-3",
      "productName": "Gaine annelée ICTA Ø20",
      "category": "Conduits & Goulottes",
      "estimatedTimeMinutes": 8,
      "laborCostPerUnit": 0.5,
      "materials": [
        {
          "id": "m8",
          "name": "Polyéthylène Haute Densité (PEHD)",
          "quantityNeeded": 0.08,
          "unit": "kg",
          "unitCost": 3.9
        },
        {
          "id": "m9",
          "name": "Fil de Tire-aiguille Acier",
          "quantityNeeded": 1,
          "unit": "m",
          "unitCost": 0.08
        }
      ],
      "is_demo": true
    }
  ],
  "manufacturingOrders": [
    {
      "id": "demo-OF-2026-001",
      "nomenclatureId": "demo-nom-1",
      "productName": "Câble Électrique Isolé 2.5mm²",
      "quantityToProduce": 5000,
      "quantityProduced": 5000,
      "quantityScrapped": 120,
      "startDate": "2026-06-20",
      "endDate": "2026-06-22",
      "assignedLine": "Ligne d'extrusion A (Sfax)",
      "assignedTeam": "Équipe Matin (Chef : J. Ben Ali)",
      "status": "Terminé",
      "advancement": 100,
      "notes": "Production conforme aux normes tunisiennes de sécurité électrique. Rebuts minimes.",
      "is_demo": true
    },
    {
      "id": "demo-OF-2026-002",
      "nomenclatureId": "demo-nom-2",
      "productName": "Disjoncteur Divisionnaire 16A",
      "quantityToProduce": 1500,
      "quantityProduced": 850,
      "quantityScrapped": 45,
      "startDate": "2026-06-25",
      "assignedLine": "Ligne Assemblage B (Tunis)",
      "assignedTeam": "Équipe Après-midi (Chef : M. Trabelsi)",
      "status": "En cours",
      "advancement": 56,
      "notes": "Cadence de montage nominale. Approvisionnement en bobines fluide.",
      "is_demo": true
    },
    {
      "id": "demo-OF-2026-003",
      "nomenclatureId": "demo-nom-3",
      "productName": "Gaine annelée ICTA Ø20",
      "quantityToProduce": 10000,
      "quantityProduced": 0,
      "quantityScrapped": 0,
      "startDate": "2026-07-02",
      "assignedLine": "Ligne Extrusion C (Sfax)",
      "assignedTeam": "Équipe Nuit (Chef : S. Ghorbel)",
      "status": "Planifié",
      "advancement": 0,
      "notes": "En attente de réception de la matière première PEHD.",
      "is_demo": true
    }
  ],
  "purchaseRequisitions": [
    {
      "id": "demo-DA-2026-001",
      "itemDescription": "Bobines de fil d'acier allié pour ressorts",
      "quantityRequested": 500,
      "unit": "kg",
      "estimatedCost": 3500,
      "requestedBy": "Kamel Slimi",
      "department": "Production - Tunis",
      "requestDate": "2026-06-22",
      "status": "En attente",
      "is_demo": true
    },
    {
      "id": "demo-DA-2026-002",
      "itemDescription": "Ordinateur portable de développement (Service IT)",
      "quantityRequested": 2,
      "unit": "u",
      "estimatedCost": 5200,
      "requestedBy": "Ines Ben Sassi",
      "department": "Système & IT",
      "requestDate": "2026-06-20",
      "status": "Approuvé",
      "decisionNotes": "Approuvé par le Directeur Général. Commande en cours.",
      "is_demo": true
    },
    {
      "id": "demo-DA-2026-003",
      "itemDescription": "Bandes de Cuivre de Contact Électrique",
      "quantityRequested": 100,
      "unit": "kg",
      "estimatedCost": 2600,
      "requestedBy": "Firas Ghorbel",
      "department": "Logistique & Stocks",
      "requestDate": "2026-06-18",
      "status": "Approuvé",
      "decisionNotes": "Stocks critiques atteints pour les disjoncteurs.",
      "is_demo": true
    }
  ],
  "purchaseOrders": [
    {
      "id": "demo-BC-2026-001",
      "supplierName": "SOTUMETAL S.A. (Tunis)",
      "itemDescription": "Cuivre Cathodique Pur de Haute Pureté",
      "quantity": 2000,
      "unitCost": 24.5,
      "vatRate": 19,
      "fodecActive": true,
      "amountHT": 49000,
      "amountTTC": 58839,
      "orderDate": "2026-06-15",
      "deliveryDueDate": "2026-06-30",
      "paymentTerms": "Chèque à 60 Jours fin de mois",
      "status": "Envoyé",
      "notes": "Livraison au dépôt de Sfax. Certificat d'analyse requis.",
      "is_demo": true
    },
    {
      "id": "demo-BC-2026-002",
      "supplierName": "TUNISIE PLASTIQUES S.A.",
      "itemDescription": "Grains PVC Isolants Auto-extinguibles",
      "quantity": 5000,
      "unitCost": 4.8,
      "vatRate": 19,
      "fodecActive": true,
      "amountHT": 24000,
      "amountTTC": 28801.2,
      "orderDate": "2026-06-10",
      "deliveryDueDate": "2026-06-25",
      "paymentTerms": "Virement bancaire BIAT comptant",
      "status": "Reçu conforme",
      "notes": "Matériaux reçus le 24/06. Inspection qualitative validée.",
      "is_demo": true
    },
    {
      "id": "demo-BC-2026-003",
      "supplierName": "COMPOSANTS ÉLECTRIQUES MED",
      "itemDescription": "Bobine de Déclenchement Magnétique 230V",
      "quantity": 1500,
      "unitCost": 1.8,
      "vatRate": 19,
      "fodecActive": false,
      "amountHT": 2700,
      "amountTTC": 3214,
      "orderDate": "2026-06-24",
      "deliveryDueDate": "2026-07-05",
      "paymentTerms": "Traite à 90 jours",
      "status": "Brouillon",
      "notes": "Vérifier la compatibilité technique du boîtier plastique.",
      "is_demo": true
    }
  ],
  "supplierPerformance": [
    {
      "id": "demo-SUP-001",
      "name": "SOTUMETAL S.A. (Tunis)",
      "category": "Cuivre, Métaux d'alliage",
      "totalVolume": 125000,
      "delayRate": 0,
      "conformityRate": 99.8,
      "score": 96,
      "status": "Rang A - Excellent",
      "is_demo": true
    },
    {
      "id": "demo-SUP-002",
      "name": "TUNISIE PLASTIQUES S.A.",
      "category": "Grains PVC, Polymères isolants",
      "totalVolume": 64000,
      "delayRate": 4.5,
      "conformityRate": 98.5,
      "score": 92,
      "status": "Rang A - Excellent",
      "is_demo": true
    },
    {
      "id": "demo-SUP-003",
      "name": "COMPOSANTS ÉLECTRIQUES MED",
      "category": "Composants de sécurité, bobines électriques",
      "totalVolume": 12400,
      "delayRate": 18.2,
      "conformityRate": 94.1,
      "score": 76,
      "status": "Rang B - Sous surveillance",
      "is_demo": true
    }
  ],
  "missions": [
    {
      "id": "demo-mo_1",
      "employeeId": "demo-emp_3",
      "employeeName": "Mohamed Ali Gharbi (Démo)",
      "vehicleId": "demo-v_1",
      "vehicleLabel": "Peugeot Partner (228 TUN 4091)",
      "startDestination": "Tunis",
      "endDestination": "Sfax",
      "departureDate": "2026-06-15",
      "returnDate": "2026-06-17",
      "purpose": "Livraison pièces techniques client Poulina Sfax",
      "status": "Approved",
      "allowancesGranted": 180,
      "expensesClaimed": [
        {
          "id": "demo-me_mo1_1",
          "category": "Hotel",
          "description": "Chambre individuelle Hôtel Sfax Centre",
          "amount": 145,
          "invoiceNumber": "FA_SFAX_998",
          "date": "2026-06-15"
        },
        {
          "id": "demo-me_mo1_2",
          "category": "Food",
          "description": "Dîner et petit-déjeuner",
          "amount": 35,
          "invoiceNumber": "RE_SFAX_321",
          "date": "2026-06-15"
        }
      ],
      "creationDate": "2026-06-12",
      "closedDate": "2026-06-18",
      "is_demo": true
    }
  ],
  "expenses": [
    {
      "id": "demo-exp_1",
      "date": "2026-06-02",
      "vehicleId": "demo-v_1",
      "vehicleLabel": "Peugeot Partner (228 TUN 4091) (Démo)",
      "category": "GasolineBonus",
      "amount": 120,
      "invoiceNb": "BON_OLA_39912",
      "providerName": "Ola Energy Charguia",
      "description": "Recharge carte carburant mensuelle",
      "is_demo": true
    }
  ],
  "incidents": [
    {
      "id": "demo-inc_1",
      "date": "2026-06-08",
      "vehicleId": "demo-v_4",
      "vehicleLabel": "Renault Clio 5 (204 TUN 1542) (Démo)",
      "employeeId": "demo-emp_3",
      "driverName": "Mohamed Ali Gharbi (Démo)",
      "description": "Choc arrière mineur au rond-point Charguia II avec un véhicule tiers",
      "safetyInquiry": "Le chauffeur prétend avoir été surpris par le freinage brusque du tiers. Constat amiable rédigé.",
      "sanctionsApplied": "Avertissement verbal sérieux rappelé. Pas de responsabilité pécuniaire directe retenue.",
      "severity": "Medium",
      "status": "Resolved",
      "is_demo": true
    }
  ],
  "cheques_effects": [
    {
      "id": "demo-chk_1",
      "number": "CH-882910",
      "bankName": "BIAT Sousse",
      "amount": 14500,
      "type": "Cheque",
      "direction": "Encaissement",
      "issuerName": "Poulina Group Holding",
      "dueDate": "2026-07-20",
      "status": "EnPortefeuille",
      "is_demo": true
    },
    {
      "id": "demo-chk_2",
      "number": "TR-554219",
      "bankName": "STB Tunis",
      "amount": 28800,
      "type": "Traite",
      "direction": "Décaissement",
      "issuerName": "TUNISIE PLASTIQUES S.A.",
      "dueDate": "2026-08-15",
      "status": "EnPortefeuille",
      "is_demo": true
    }
  ],
  "bank_audits": [
    {
      "id": "demo-aud_1",
      "auditDate": "2026-06-30",
      "period": "Q2 2026",
      "bankAccount": "BIAT 08000123456789",
      "auditedFees": 340.5,
      "contestedFees": 120,
      "status": "Regularized",
      "is_demo": true
    }
  ],
  "juridique_shareholders": [
    {
      "id": "demo-jur_sh1",
      "name": "M. Mohamed Hédi Ben Ammar",
      "shareCount": 6000,
      "percentage": 60,
      "nominalValue": 10,
      "type": "Physique",
      "is_demo": true
    },
    {
      "id": "demo-jur_sh2",
      "name": "Sté Elyssa Investments SARL",
      "shareCount": 4000,
      "percentage": 40,
      "nominalValue": 10,
      "type": "Morale",
      "is_demo": true
    }
  ],
  "juridique_deadlines": [
    {
      "id": "demo-jur_dl1",
      "title": "Dépôt des comptes annuels au RNE",
      "dueDate": "2026-07-31",
      "category": "Fiscal & Légal",
      "status": "Pending",
      "is_demo": true
    }
  ],
  "juridique_documents": [
    {
      "id": "demo-jur_doc1",
      "title": "Procès-Verbal de l'Assemblée Générale Ordinaire 2025",
      "date": "2026-05-15",
      "type": "PV AGO",
      "fileUrl": "#",
      "is_demo": true
    }
  ],
  "caisse_transactions": [
    {
      "id": "demo-pos_tx1",
      "timestamp": "2026-06-25 14:30",
      "totalTTC": 185.4,
      "paymentMethod": "Espèces",
      "operatorName": "Caissier 1",
      "is_demo": true
    }
  ],
  "attendance_records": [
    {
      "id": "demo-att_1",
      "employeeId": "demo-emp_1",
      "employeeName": "Khaled Ben Amor",
      "date": "2026-06-24",
      "checkIn": "08:02",
      "checkOut": "17:05",
      "status": "Present",
      "is_demo": true
    }
  ]
};
